### ISSUE TITLE
Main Task List

### ISSUE THREAD

**Issue by satadhi** [satadhi/amazon-clone#3]
## Big Ideas
- [ ] **TopMenu bar**: show number of items in the card in the 
- [ ] language support ?
- [ ] For items add paginations 
- [ ] Check out the new image format i.e; google image format that is cool
- [ ] Checkout react-currency-format
- [ ] loaders ??
- [ ] payment gatway
- [ ] error page 
- [ ] https://www.prisma.io/

## header

- [x] #5
- [ ] implement search button + add debouncing

## Home page

- [x] Shrink blank spaces to 0 then start shrinking the home materials
- [ ] Make the background image mid to bottom faded
- [ ] Add to Basket button are not align
- [ ] login system ?
## Checkout page
- [x] #4
- [x] #6
- [ ] When no Item show error gracefully
- [ ] Add functionality for delete button +  quantity button

## Item detail page
- [ ] #7
- [ ] implement buttons functionality
